fragment BlogParts on Blog {
  __typename
  title
  excerpt
  date
  slug
  category
  image
  imageAlt
  body
}

fragment ProductParts on Product {
  __typename
  title
  slug
  tagline
  description
  image
  imageAlt
  features {
    __typename
    icon
    text
  }
  faqs {
    __typename
    q
    a
  }
  body
}

fragment HomepageParts on Homepage {
  __typename
  heroSpring {
    __typename
    headline
    sub
    cta
    heroImage
  }
  heroSummer {
    __typename
    headline
    sub
    cta
    heroImage
  }
  heroFall {
    __typename
    headline
    sub
    cta
    heroImage
  }
  heroWinter {
    __typename
    headline
    sub
    cta
    heroImage
  }
  heroSevere {
    __typename
    headline
    sub
    cta
    heroImage
  }
  heroHeatwave {
    __typename
    headline
    sub
    cta
    heroImage
  }
  statsLine
  trustBar {
    __typename
    icon
    label
  }
  processSteps {
    __typename
    icon
    title
    body
  }
  featuredProducts {
    __typename
    slug
    badge
  }
  reviews {
    __typename
    name
    hood
    stars
    text
  }
  ctaHeadline
  ctaBody
}

fragment FaqParts on Faq {
  __typename
  categories {
    __typename
    category
    items {
      __typename
      q
      a
    }
  }
}

fragment NeighborhoodsParts on Neighborhoods {
  __typename
  name
  slug
  headline
  intro
  longDesc
  faqs {
    __typename
    q
    a
  }
}

fragment SettingsParts on Settings {
  __typename
  siteName
  phone
  email
  address
  city
  state
  zip
  nav {
    __typename
    label
    href
  }
}
