fragment BlogParts on Blog {
  __typename
  title
  excerpt
  date
  slug
  category
  image
  imageAlt
  body
}

fragment ProductParts on Product {
  __typename
  title
  slug
  tagline
  description
  image
  imageAlt
  features {
    __typename
    icon
    text
  }
  faqs {
    __typename
    q
    a
  }
  body
}

fragment HomepageParts on Homepage {
  __typename
  heroSpring {
    __typename
    headline
    sub
    cta
  }
  heroSummer {
    __typename
    headline
    sub
    cta
  }
  heroFall {
    __typename
    headline
    sub
    cta
  }
  heroWinter {
    __typename
    headline
    sub
    cta
  }
  heroSevere {
    __typename
    headline
    sub
    cta
  }
  heroHeatwave {
    __typename
    headline
    sub
    cta
  }
  reviews {
    __typename
    name
    hood
    stars
    text
  }
  ctaHeadline
  ctaBody
}

fragment SettingsParts on Settings {
  __typename
  siteName
  phone
  email
  address
  city
  state
  zip
  nav {
    __typename
    label
    href
  }
}
