[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENV = "preview"
